# Generated by Django 6.1.1 on 2026-09-24 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def mark_existing_chefs_as_approved(apps, schema_editor):
    Profile = apps.get_model("home", "Profile")
    approved_at = timezone.now()
    Profile.objects.filter(role="chef").update(
        chef_approval_status="approved",
        chef_requested_at=approved_at,
        chef_approved_at=approved_at,
    )
    Profile.objects.exclude(role="chef").update(
        chef_approval_status=None,
        chef_requested_at=None,
        chef_approved_at=None,
        chef_approved_by=None,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="chef_approval_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                help_text="Only approved chefs can sign in to chef tools.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="chef_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="chef_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_chef_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="chef_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_chefs_as_approved, migrations.RunPython.noop),
    ]
