# Generated by Django 6.1.1 on 2026-09-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_chef_approval_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefProfile',
            fields=[
            ],
            options={
                'verbose_name': 'chef profile',
                'verbose_name_plural': 'chef profiles',
                'ordering': ['-chef_requested_at', 'user__username'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.profile',),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
                'ordering': ['user__username'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.profile',),
        ),
    ]
