# Generated by Django 6.1.1 on 2026-09-28 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_comment_notification_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Set when this comment is a reply to another comment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='vege.comment'),
        ),
    ]
