# Generated by Django 6.1.1 on 2026-09-28 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='chef',
            new_name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, help_text='Comment/reply that triggered this notification; deleting it removes the notification too.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vege.comment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('reply', 'Reply')], max_length=10),
        ),
    ]
